### PR TITLE
Cleanup

### LINKED ISSUE #42: Referenced NuGet packages
This is just a suggestion and it would make it a bit easier (for me) to contribute. As I can see, the CI scripts run an explicit `NuGet restore` and Visual Studio 2015 is now also able to restore the NuGet packages automatically, so I would suggest to remove them from the repository. I am happy to provide a pull request, if this is acceptable.

### PR DESCRIPTION
**Pull request by pragmatrix**
This PR removes the NuGet packages and normalizes the line endings for the remaining two files. Fixes #42.

### CODE REVIEW

**Comment by danbarua** [comment]
Woops, we need the `/.nuget` folder for the Mono build on Travis
Otherwise LGTM.

(We need the mono build on Travis because AppVeyor chokes on tests with lots of async.)

**Comment by pragmatrix** [comment]
I've fixed travis nuget restore and the xunit test-runner dependency, but three of the tests fail now. Any ideas?

**Comment by danbarua** [comment]
It could just be a transient timeout, I've not seen them on Travis up til now, only AppVeyor.

**Comment by danbarua** [comment]
:shipit: Great, thanks for the PR! :+1:

**Comment by pragmatrix** [comment]
YW!, and I tried the commit before this PR. It also had 2 failures: https://travis-ci.org/pragmatrix/NEventSocket/builds/137848571

**Pull request merged**
